/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type Position = number[];
export type Rotation = number[];
export type Scaling = number[];
export type Type = string;
export type Type1 = string;
export type Direction = number[];
export type Intensity = number;
export type Position1 = number[] | null;
export type Diffuse = number[];
export type Emissive = number[];
export type Specular = number[];
export type Entities = Entity[];

export interface Scene {
  entities?: Entities;
  [k: string]: unknown;
}
export interface Entity {
  id: Id;
  name: Name;
  components: Components;
  [k: string]: unknown;
}
export interface Components {
  transform?: TransformComponent | null;
  mesh?: MeshComponent | null;
  light?: LightComponent | null;
  material?: MaterialComponent | null;
  [k: string]: unknown;
}
export interface TransformComponent {
  position?: Position;
  rotation?: Rotation;
  scaling?: Scaling;
  [k: string]: unknown;
}
export interface MeshComponent {
  type: Type;
  properties?: Properties;
  [k: string]: unknown;
}
export interface Properties {
  [k: string]: unknown;
}
export interface LightComponent {
  type: Type1;
  direction?: Direction;
  intensity?: Intensity;
  position?: Position1;
  [k: string]: unknown;
}
export interface MaterialComponent {
  diffuse?: Diffuse;
  emissive?: Emissive;
  specular?: Specular;
  [k: string]: unknown;
}
